### ISSUE TITLE
state-custom-ui is not loading/working on HA 0.115.x

### ISSUE THREAD

**Issue by poudenes** [andrey-git/home-assistant-custom-ui#193]
After the update to 0.115.x the state custom ui is not loading anymore

```
2020-09-19 08:54:45 ERROR (MainThread) [homeassistant.setup] Error during setup of component customizer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/customizer/__init__.py", line 71, in async_setup
    add_extra_html_url('/local/custom_ui/state-card-custom-ui')
  File "/config/custom_components/customizer/__init__.py", line 63, in add_extra_html_url
    frontend.add_extra_html_url(
AttributeError: module 'homeassistant.components.frontend' has no attribute 'add_extra_html_url'
```

**Comment by poudenes** [comment]
use this one and it work again:

https://github.com/Mariusthvdb/custom-ui
